Repository DeveloperAcademy-POSTECH/MC3-Team16-QAQA, pull requests merged in 2023-07, with the labels that each got.

#5 [Feat] GameCenter 연결
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/QAQA.entitlements
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Resources/Assets.xcassets/homeQuokka.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/homeQuokka.imageset/자산 3@4x 2.png
  QAQA/QAQA/Resources/Assets.xcassets/homeQuokka.imageset/자산 3@4x 2@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/homeQuokka.imageset/자산 3@4x 2@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/testBlue.colorset/Contents.json
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+Friends.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKGameCenterViewController.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKLocalPlayerListener.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchmakerViewControllerDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/Utils/Utils.swift
  QAQA/QAQA/View/ContentView.swift
  QAQA/QAQA/View/GameView.swift
  QAQA/QAQA/View/HomeView.swift
Labels: ✨ Feat, 🐙 West

#8 [Feat] TimerView 구현
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Model.swift
  QAQA/QAQA/Model/TimerModel.swift
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Utils/UIScreen/UIScreen+Extension.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/TimerModalView.swift
  QAQA/QAQA/View/Question/TimerView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#15 Feat/#11
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/TimerModel.swift
  QAQA/QAQA/Resources/Assets.xcassets/Color/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/finishButton.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/pause.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/pauseButton.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/reactionGood.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/reactionQuestion.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/testBlue.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonGood.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonGood.imageset/goodButton 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonGood.imageset/goodButton 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonGood.imageset/goodButton 3.png
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonQuestion.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonQuestion.imageset/badButton 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonQuestion.imageset/badButton 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/buttonQuestion.imageset/badButton.png
  QAQA/QAQA/Resources/Assets.xcassets/button/eva.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/eva.imageset/eva 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/eva.imageset/eva 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/eva.imageset/eva.png
  QAQA/QAQA/Resources/Assets.xcassets/button/greenButton.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/greenButton.imageset/greenButton 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/greenButton.imageset/greenButton 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/greenButton.imageset/greenButton.png
  QAQA/QAQA/Resources/Assets.xcassets/button/kingjung.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/kingjung.imageset/kingjung 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/kingjung.imageset/kingjung 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/kingjung.imageset/kingjung.png
  QAQA/QAQA/Resources/Assets.xcassets/button/orangeButton.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/orangeButton.imageset/orangeButton 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/orangeButton.imageset/orangeButton 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/orangeButton.imageset/orangeButton.png
  QAQA/QAQA/Resources/Assets.xcassets/button/questionMark.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/questionMark.imageset/questionMark 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/questionMark.imageset/questionMark 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/questionMark.imageset/questionMark.png
  QAQA/QAQA/Resources/Assets.xcassets/button/star.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/star.imageset/star 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/star.imageset/star 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/star.imageset/star.png
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/Utils/ReactionModifier/ReactionModifier.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionView.swift
  QAQA/QAQA/View/Question/TimerModalView.swift
  QAQA/QAQA/View/Question/TimerView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#16 [Feat] Hint Modal 생성
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA.xcodeproj/xcshareddata/xcschemes/QAQA.xcscheme
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Model/Question/HintModel.swift
  QAQA/QAQA/Model/Question/HintState.swift
  QAQA/QAQA/Model/Timer/TimerModel.swift
  QAQA/QAQA/View/Question/HintModal.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Timer/TimerModalView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
  QAQA/QAQA/ViewModel/HintViewModel.swift
  QAQA/QAQA/ViewModel/ViewModel.swift
Labels: 🐳 Molly, ✨ Feat

#20 [Fix] 끝내기 버튼 오류 해결
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  QAQA/QAQA/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: 🚑️ Hotfix, 🐙 West

#23 [Feat] 끝내기 모달 추가
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Resources/Assets.xcassets/Color/finishButtonColor.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/pauseButtonColor.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/pauseTextColor.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/reactionGoodColor.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/reactionQuestionColor.colorset/Contents.json
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionView.swift
  QAQA/QAQA/View/Timer/TimerModalView.swift
Labels: ✏️ Chore, 🦈 Kiyoung

#24 [Feat] QuestionView 질문 힌트 UI 변경
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/View/Question/HintView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: 🐳 Molly, ✨ Feat

#26 [Feat] 끝내기 버튼 연동
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionView.swift
Labels: ✨ Feat, 🐙 West

#31 [Feat] 리액션 버튼 연동
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: ✨ Feat, 🐙 West

#33 [Feat] 타이머 모달 기능 화면간 공유
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Model/Timer/TimerModel.swift
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Timer/TimerModalView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#34 [Del] GameCenter 코드 주석 제거
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Model/Timer/TimerModel.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+Friends.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKGameCenterViewController.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKLocalPlayerListener.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchmakerViewControllerDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Timer/TimerModalView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: 🗑️ Del, 🐙 West

#37 [Feat] 전체적인 뷰 업데이트
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  QAQA/QAQA/Info.plist
  QAQA/QAQA/Resources/Assets.xcassets/Color/hintViewOrange.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/hintViewYellow.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/pauseButtonYellow.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/endButton.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/endButton.imageset/endButton4 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/endButton.imageset/endButton4 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/endButton.imageset/endButton4.png
  QAQA/QAQA/Resources/Assets.xcassets/button/finishButton_Red.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/finishButton_Red.imageset/endButton_Red.png
  QAQA/QAQA/Resources/Assets.xcassets/button/finishButton_Red.imageset/endButton_Red@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/button/finishButton_Red.imageset/endButton_Red@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/button/randomHintButton.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/randomHintButton.imageset/randomHintButton 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/randomHintButton.imageset/randomHintButton 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/randomHintButton.imageset/randomHintButton.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Bad.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Bad.imageset/reactionButton_Bad 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Bad.imageset/reactionButton_Bad 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Bad.imageset/reactionButton_Bad.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Good.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Good.imageset/reactionButton_Good 1.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Good.imageset/reactionButton_Good 2.png
  QAQA/QAQA/Resources/Assets.xcassets/button/reactionButton_Good.imageset/reactionButton_Good.png
  QAQA/QAQA/Resources/Assets.xcassets/outroInfoViewQaqa.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/outroInfoViewQaqa.imageset/outroInfoViewQaqa.png
  QAQA/QAQA/Resources/Assets.xcassets/outroInfoViewQaqa.imageset/outroInfoViewQaqa@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroInfoViewQaqa.imageset/outroInfoViewQaqa@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/questionBubble.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/questionBubble.imageset/questionBubble.png
  QAQA/QAQA/Resources/Assets.xcassets/questionBubble.imageset/questionBubble@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/questionBubble.imageset/questionBubble@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/questionQaqa.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/questionQaqa.imageset/questionQaqa 1.png
  QAQA/QAQA/Resources/Assets.xcassets/questionQaqa.imageset/questionQaqa 2.png
  QAQA/QAQA/Resources/Assets.xcassets/questionQaqa.imageset/questionQaqa.png
  QAQA/QAQA/Utils/Font/BMJUAOTF.otf
  QAQA/QAQA/Utils/Font/TalkFile_BMJUA_otf.otf.otf
  QAQA/QAQA/View/Outro/OutroInfoView.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/HintView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionLottieView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: 🐳 Molly, ✨ Feat

#35 [Feat] Gyroscope 를 이용한 인트로게임 기능구현
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Resources/Assets.xcassets/back_1.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/back_1.imageset/back_1.jpg
  QAQA/QAQA/Resources/Assets.xcassets/back_2.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/back_2.imageset/back_2.jpg
  QAQA/QAQA/Resources/Assets.xcassets/boom_1.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/boom_1.imageset/boom_1.png
  QAQA/QAQA/Resources/Assets.xcassets/boom_2.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/boom_2.imageset/boom_2.png
  QAQA/QAQA/Resources/Assets.xcassets/sky_1.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/sky_1.imageset/sky_1.jpeg
  QAQA/QAQA/Resources/Assets.xcassets/smile_1.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/smile_1.imageset/smile_1.png
  QAQA/QAQA/Utils/Gyroscopes/Ball.swift
  QAQA/QAQA/Utils/Gyroscopes/BallContainerView.swift
  QAQA/QAQA/Utils/Gyroscopes/Content_test.swift
  QAQA/QAQA/Utils/Gyroscopes/GyroscopeManager.swift
  QAQA/QAQA/Utils/HapticManager/HapticFeedbackManager.swift
  QAQA/QAQA/Utils/HapticManager/HapticMotion.swift
  QAQA/QAQA/Utils/HapticManager/HapticTestView.swift
Labels: ✨ Feat, 🐡 Joy

#42 [Feat] 타이머 코드 개선 및 연동
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#44 [Feat]#41 햅틱 리액션 연동 완료
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/Utils/HapticManager/HapticFeedbackManager.swift
  QAQA/QAQA/Utils/HapticManager/HapticMotion.swift
  QAQA/QAQA/Utils/HapticManager/HapticTestView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: ✨ Feat, 🐡 Joy

#46 [Feat] OutroView 업데이트 및 다크모드 비활성화
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Info.plist
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroViewGaugeGray.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroViewGray.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroViewYellow.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/OutroQaqa.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/OutroQaqa.imageset/OutroQaqa.png
  QAQA/QAQA/Resources/Assets.xcassets/OutroQaqa.imageset/OutroQaqa@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/OutroQaqa.imageset/OutroQaqa@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/button/backToHomeButton_Yellow.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/backToHomeButton_Yellow.imageset/backToHomeButton_Yellow.png
  QAQA/QAQA/Resources/Assets.xcassets/button/backToHomeButton_Yellow.imageset/backToHomeButton_Yellow@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/button/backToHomeButton_Yellow.imageset/backToHomeButton_Yellow@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Green.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Green.imageset/outroResultRectangle_Green.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Green.imageset/outroResultRectangle_Green@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Green.imageset/outroResultRectangle_Green@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Orange.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Orange.imageset/outroResultRectangle.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Orange.imageset/outroResultRectangle@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Orange.imageset/outroResultRectangle@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Yellow.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Yellow.imageset/outroResultRectangle_Yellow.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Yellow.imageset/outroResultRectangle_Yellow@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/outroResultRectangle_Yellow.imageset/outroResultRectangle_Yellow@3x.png
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/View/Outro/OutroCardView.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Outro/OutroResultCardView.swift
Labels: 🐳 Molly, ✨ Feat

#50 feat/#47 리액션 버그 고침
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: ✨ Feat, 🐡 Joy

#51 [Feat] OutroView Gauge 구현 및 변수데이터 연동
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Outro/OutroEndingModel.swift
  QAQA/QAQA/Model/Question/HintModel.swift
  QAQA/QAQA/Model/Question/HintState.swift
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroGaugeGray.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroGaugeGreen.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroGaugeLightGreen.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroGaugeLightYellow.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/Color/outroGaugeYellow.colorset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/nextButton.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/button/nextButton.imageset/nextButton.png
  QAQA/QAQA/Resources/Assets.xcassets/button/nextButton.imageset/nextButton@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/button/nextButton.imageset/nextButton@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/introResultQaqa.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/introResultQaqa.imageset/introResultQaqa.png
  QAQA/QAQA/Resources/Assets.xcassets/introResultQaqa.imageset/introResultQaqa@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/introResultQaqa.imageset/introResultQaqa@3x.png
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/View/IntroResultView.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Question/HintView.swift
  QAQA/QAQA/ViewModel/HintViewModel.swift
  QAQA/QAQA/ViewModel/OutroEndingViewModel.swift
Labels: 🐳 Molly, ✨ Feat

#53 [Feat] 리액션 스코어 구현
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Model/Outro/OutroEndingModel.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Outro/OutroInfoView.swift
  QAQA/QAQA/View/Outro/OutroResultCardView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionView.swift
  QAQA/QAQA/ViewModel/OutroEndingViewModel.swift
  QAQA/QAQA/ViewModel/OutroViewModel.swift
Labels: ✨ Feat, 🐙 West

#57 [Feat] 킹정킹, 에바킹 구현
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Outro/OutroInfoView.swift
  QAQA/QAQA/View/Outro/OutroResultCardView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
Labels: ✨ Feat, 🐙 West
