Repository DeveloperAcademy-POSTECH/MC3-Team16-QAQA, pull requests merged in 2023-08, with the labels that each got.

#63 [Feat] HomeView, TutorialView, Launch Screen 추가
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Info.plist
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Resources/Assets.xcassets/AppIconLaunch.imageset/AppIconLaunch.png
  QAQA/QAQA/Resources/Assets.xcassets/AppIconLaunch.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/bombQuokka.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/bombQuokka.imageset/bombQuokka.png
  QAQA/QAQA/Resources/Assets.xcassets/homeViewButton_Green.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/homeViewButton_Green.imageset/onBoardingButton_Green_default.png
  QAQA/QAQA/Resources/Assets.xcassets/homeViewButton_Green.imageset/onBoardingButton_Green_default@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/homeViewButton_Green.imageset/onBoardingButton_Green_default@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/homeViewImg.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/homeViewImg.imageset/StartImg.png
  QAQA/QAQA/Resources/Assets.xcassets/resultQuokka.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/resultQuokka.imageset/resultQuokka.png
  QAQA/QAQA/Resources/Assets.xcassets/talkingQuokka.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/talkingQuokka.imageset/talkingQuokka.png
  QAQA/QAQA/Resources/Assets.xcassets/tutorialViewButton_Yellow.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/tutorialViewButton_Yellow.imageset/onBoardingButton_Yellow_default.png
  QAQA/QAQA/Resources/Assets.xcassets/tutorialViewButton_Yellow.imageset/onBoardingButton_Yellow_default@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/tutorialViewButton_Yellow.imageset/onBoardingButton_Yellow_default@3x.png
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Home/TutorialView.swift
Labels: ✨ Feat, 🐟 Claudia

#61 [Feat] 폭탄 돌리기 게임 연동
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/Utils/Gyroscopes/BallContainerView.swift
  QAQA/QAQA/Utils/Gyroscopes/Content_test.swift
  QAQA/QAQA/Utils/Gyroscopes/GyroscopeManager.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Test/TestIntroStartView.swift
  QAQA/QAQA/View/Test/TestingIntroGame.swift
  QAQA/QAQA/View/Test/TestingResultView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#65 [Refactor] 필요없는 파일 삭제 및 코드 수정
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Model/Outro/.gitkeep
  QAQA/QAQA/Model/Outro/OutroCardModel.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/HintView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Question/ReactionView.swift
Labels: ♻️ Refactor, 🐙 West

#70 [Hotfix] 게임 시작 안됨 오류 해결
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/QAQAApp.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Intro/BeginIntroModalView.swift
  QAQA/QAQA/View/Intro/BeginQuestionModalView.swift
Labels: 🐳 Molly, 🚑️ Hotfix

#72 [Feat] BeginQuestionModalView 시작하기 버튼 터치 시 질문시작 연동
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Intro/BeginQuestionModalView.swift
  QAQA/QAQA/View/Intro/IntroResultView.swift
  QAQA/QAQA/View/Question/FinishModalView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: 🐳 Molly, ✨ Feat

#73 [Feat] 게임 전 카운트 다운 화면 적용
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Resources/Assets.xcassets/countDownBackground.imageset/Contents.json
  QAQA/QAQA/Resources/Assets.xcassets/countDownBackground.imageset/countDownBackground 1.png
  QAQA/QAQA/Resources/Assets.xcassets/countDownBackground.imageset/countDownBackground 2.png
  QAQA/QAQA/Resources/Assets.xcassets/countDownBackground.imageset/countDownBackground.png
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+GKMatchDelegate.swift
  QAQA/QAQA/Utils/GameCenter/RealTimeGame+MatchData.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Intro/BeginIntroModalView.swift
  QAQA/QAQA/View/IntroGame/BallContainerView.swift
  QAQA/QAQA/View/IntroGame/IntroGameView.swift
  QAQA/QAQA/View/IntroGame/StartCountDownView.swift
Labels: ✨ Feat, 🦈 Kiyoung

#78 [Chore] OutroView UI 수정
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/Resources/Assets.xcassets/AppIconLaunch.imageset/AppIconLaunch.png
  QAQA/QAQA/Resources/Assets.xcassets/AppIconLaunch.imageset/AppIconLaunch@2x.png
  QAQA/QAQA/Resources/Assets.xcassets/AppIconLaunch.imageset/AppIconLaunch@3x.png
  QAQA/QAQA/Resources/Assets.xcassets/Color/backgroundYellow.colorset/Contents.json
  QAQA/QAQA/Utils/Color/Color+Extension.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/Outro/OutroEndingView.swift
  QAQA/QAQA/View/Outro/OutroResultCardView.swift
Labels: ✏️ Chore, 🐙 West

#81 [Fix]IntroGame 폭탄 버그, 타이머 버그 수정
  QAQA/QAQA.xcodeproj/project.pbxproj
  QAQA/QAQA/Model/Game/RealTimeGame.swift
  QAQA/QAQA/View/Home/HomeView.swift
  QAQA/QAQA/View/IntroGame/BallContainerView.swift
  QAQA/QAQA/View/IntroGame/IntroGameView.swift
  QAQA/QAQA/View/IntroGame/StartCountDownView.swift
  QAQA/QAQA/View/Question/QuestionView.swift
  QAQA/QAQA/View/Test/TestIntroStartView.swift
  QAQA/QAQA/View/Timer/TimerNoCountView.swift
  QAQA/QAQA/View/Timer/TimerView.swift
Labels: 🛠️ Fix, 🦈 Kiyoung
